import type { DiffTriage, PullRef } from "@git-investigator/core/diff/types";
import type { RepoRef } from "@git-investigator/core/types";
import type { ViewArtifact, ViewClause, ViewGap } from "../../../line-investigation/model/types";
import type { CoverageItem } from "./coverage-item";
import type { DerivedConfidence } from "./derived-confidence";
import type { PrClause } from "./pr-clause";
import type { PrRegion } from "./pr-region";
import type { UpstreamCounts } from "./upstream-counts";

export type PrView = {
  mode: "synthesized" | "evidence-only";
  repo: RepoRef;
  pr: PullRef;
  datum: { time: number; label: "head" | "today" };
  regions: PrRegion[];
  artifacts: ViewArtifact[];
  gaps: ViewGap[];
  clauses: PrClause[];
  findingClauses: ViewClause[];
  regionsOf: Map<string, string[]>;
  explained: number;
  files: number;
  added: number | null;
  removed: number | null;
  upstream: UpstreamCounts;
  coverage: CoverageItem[];
  confidence: DerivedConfidence | null;
  triage: DiffTriage;
  error: string | null;
};
